# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "fantomas";
    version = "6.3.4";
    sha256 = "1bf57pzvl0i1bgic2vf08mqlzzbd5kys1ip9klrhm4f155ksm9fm";
  })
  (fetchNuGet {
    pname = "fsharp-analyzers";
    version = "0.26.0";
    sha256 = "0xgv5kvbwfdvcp6s8x7xagbbi4s3mqa4ixni6pazqvyflbgnah7b";
  })
  (fetchNuGet {
    pname = "FsUnit";
    version = "6.0.0";
    sha256 = "18q3p0z155znwj1l0qq3vq9nh9wl2i4mlfx4pmrnia4czr0xdkmb";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "17.10.0";
    sha256 = "0s0v7jmrq85n356xv7zixvwa4z94fszjcr5vll8x4im1a2lp00f9";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "17.10.0";
    sha256 = "13g8fwl09li8fc71nk13dgkb7gahd4qhamyg2xby7am63nlchhdf";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.10.0";
    sha256 = "07j69cw8r39533w4p39mnj00kahazz38760in3jfc45kmlcdb26x";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "17.10.0";
    sha256 = "1bl471s7fx9jycr0cc8rylwf34mrvlg9qn1an6l86nisavfcyb7v";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    sha256 = "0fijg0w6iwap8gvzyjnndds0q4b8anwxxvik7y8vgq97dram4srb";
  })
  (fetchNuGet {
    pname = "NUnit";
    version = "4.1.0";
    sha256 = "0fj6xwgqaxq3mrai86bklclfmjkzf038mrslwfqf4ignaz9f7g5j";
  })
  (fetchNuGet {
    pname = "NUnit3TestAdapter";
    version = "4.5.0";
    sha256 = "1srx1629s0k1kmf02nmz251q07vj6pv58mdafcr5dr0bbn1fh78i";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    sha256 = "1wdbavrrkajy7qbdblpbpbalbdl48q3h34cchz24gvdgyrlf15r4";
  })
]
